config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index] do
    resources :groups, only: [:index, :new, :create, :show] do
      resources :payments, only: [:new, :create]
    end
  end

  root 'users#index' # This sets the root path to the UsersController#index action.
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :payment_items, dependent: :delete_all
  has_many :payments, through: :payment_items, dependent: :delete_all
  has_one_attached :icon

  validates :icon, presence: true
  validates :name, presence: true

  def total_amount_by_group(group_id)
    payments.joins(:payment_items).where(payment_items: { group_id: }).sum('payments.amount')
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @groups = current_user.groups.all.includes(:payments)
  end

  def new
    @user = current_user
    @group = Group.new
  end

  def show
    @user = current_user
    @group = Group.find(params[:id])
    @payments = @group.payments.order('created_at DESC')
  end

  def create
    @user = current_user
    @group = Group.new(
      name: new_group_params['name'],
      icon: new_group_params['icon'],
      user_id: current_user.id
    )
    if @group.save
      flash[:success] = 'You successfully created new Category'
      redirect_to user_groups_path(user_id: current_user.id)
    else
      flash[:alert] = 'Category was not created'
    end
  end

  def new_group_params
    params.require(:new_group).permit(:name, :icon)
  end
end

app/views/groups/index.html.erb
<%= render partial: '/groups/partials/nav', locals: { title: 'Budget Categories', backurl: user_groups_path(user_id: current_user.id) } %>

<div class="container">
  <% @groups.each do |group| %>
    <%= link_to user_group_path(user_id: @user.id, id: group.id), class: 'custom-links' do %>
      <div class="image"><%= image_tag group.icon if group.icon.attached? %></div>
      <div class="category_flex">
      <div class="name">
        <h3><%= group.name %></h3>
      </div>
       <div class="transaction_detail">
        <p><%=group.created_at.strftime('%d %B %Y')%></p>
       </div>
</div>
      <div class="total">$<%= '%.2f' % group.total_amount_by_group(group.id) %></div>
    <% end %>
  <% end %>

  <button class="new-category-button">
    <%= link_to 'ADD CATEGORY', new_user_group_path(user_id: current_user.id) %>
  </button>
</div>

app/views/groups/new.html.erb
<%= render partial: 'groups/partials/form', locals: { group:@group }%>

app/views/groups/show.html.erb
<section class="group_detail">
<header>
  <div class="title">
    <div><%= link_to user_groups_path do %>
      <%= content_tag(:div) do %>
      <i class="icons">BACK</i>
      <% end %>
      <% end %></div>
    <div>
      <h2><%=@group.name%></h2>
    </div>
  </div>
</header>

<div class="group_holder">
  <div class="group_card">
    <div class="card_element">
      <div class="picture_holder">
        <img src=<%= @group.icon %> alt="group picture">
      </div>
      <div class="name_holder">
        <h5 class="group_name">
          <%=@group.name%>
        </h5>
        <p class="detail_description">Group expenses description</p>
      </div>
    </div>
    <hr>
    <div>
      <% @payments.each do |payment| %>
      <div class="transaction">
        <p>Transaction No <%=payment.id%></p>
        <div class="transaction_detail">
          <p><%=payment.created_at.strftime('%d %B %Y')%></p>
          <p>$<%=payment.amount%></p>
        </div>
      </div>
      <% end %>
    </div>
    <hr>
    <div class="total_transaction">
      <h5 class="total">TOTAL PAYMENT</h5>
      <h5 class="total">$<%=number_with_delimiter(@group.total_amount_by_group(@group.id))%></h5>
    </div>
  </div>
</div>
</div>
  <div>
    <button class="new-category-button"><%= link_to "Add a new transaction", new_user_group_payment_path(current_user,@group), class: "button_text" %></button>
  </div>
  </section>