config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index] do
    resources :groups, only: [:index, :new, :create, :show] do
      resources :payments, only: [:new, :create]
    end
  end

  root 'users#index' # This sets the root path to the UsersController#index action.
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :groups, through: :payment_items
  has_many :payment_items

  validates :amount, presence: true
  validates :name, presence: true
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  # before_action :authenticate_user!

  def index
    @group = Group.find(params[:group_id])
    @payments = @group.payments.order(created_at: :desc)
  end

  def new
    @payment = current_user.payments.new
    @group = Group.find(params[:group_id])
    @groups = current_user.groups
  end

  def create
    @payment = Payment.new(name: payment_params[:name], amount: payment_params[:amount], author_id: current_user.id)
    @group = Group.find(params[:group_id])

    if @payment.save
      @payment_item = PaymentItem.new(payment_id: @payment.id, group_id: params[:payment_item][:group_id])

      redirect_to user_group_path(current_user, @group), notice: 'Payment successfully created.' if @payment_item.save

    else
      render :new, status: :unprocessable_entity
    end
  end

  def payment_params
    params.require(:payment_item).permit!
  end
end

app/views/payments/new.html.erb
<%= form_with model: [current_user, @group, Payment.new], url: user_group_payments_path(current_user, @group) do |form| %>


<header>
    <div class="form-title title">
      <div ><%= link_to(:back) do %>
        <%= content_tag(:div) do %>
          <i class="material-icons">BACK</i>
        <% end %>
      <% end %></div>
      <div><h2>New Payment</h2></div>
      <div><%= form.submit "Submit" %></div>
    </div>
  </header>

<div class="form-body">
  <%= form_with url: user_group_payments_path(current_user, group_id:@group.id), method: :post,
  scope: :payment_item , local: true, class: "category-form" do |f| %>
  <div class="form-field">
    <%= f.text_field :name, required:true,
    placeholder:'Enter Name',class:'custom-form-field-text' %>
  </div>
  
  <div class="form-field">
  <%= f.number_field :amount, step:0.15,min:0 , required:true,
    placeholder:'Enter Amount', class:'custom-form-field-text' %>
  </div>

  <div class="form-field-selection">
  <%= f.collection_select :group_id, @current_user.groups, :id, :name, { prompt: 'Select a group' }, required: true %>
  </div>
  <% end %>
  <% end %>
</div>